### ISSUE TITLE
Accuracy only 50% for sst-2 

### ISSUE THREAD

**Issue by yifei1349** [WadeYin9712/SentiBERT#10]
Hello,
I followed all the process as written in the GitHub page. But I got only 51% accuracy for sst-2 task.
Then I tried checkpoints offered by your teams and didn't train by myself, which means I only do preprocessing and evaluation, and the results are still about 50%. And my colleague met the same problem.
Do anyone met the same condition? What could possible be the problem?

**Comment by WadeYin9712** [comment]
Hi lfei! Thanks for your interest! I just wonder if our model could work on other tasks or not from your side.

**Comment by yifei1349** [comment]
Thank you for your kind reply and useful instructions.
The main reason is that we use the latest corenlp but not the version that you use.
But we still got some other problems (something still mistery for us). We are trying to find them out......
