### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by dsekar189** [WadeYin9712/SentiBERT#2]
Hey, thank you for the work! While training sst2, i came upon the FileNotFountError: [Errno 2] No such file or directory: '/stanford-corenlp-full-2018-10-05/sst2_train_text.txt.json'. Although, this json was created in the previous step and stored in the same directory i.e., in the stanford-corenlp-full-2018-10-05 folder. Any assistance would be of great help! Thank you!

**Comment by WadeYin9712** [comment]
Hi, Thanks for your interest! Could you try to use absolute path rather than '/stanford-corenlp-full-2018-10-05/sst2_train_text.txt.json'? I think it will work. Thanks!

**Comment by dsekar189** [comment]
I did try adding the absolute path for both data_dir and tree_dir. I got a "Segmentation fault (core dumped)" displayed. Could it be because of the RAM usage? Also, thank you for the reply!

**Comment by WadeYin9712** [comment]
Perhaps...... When I tried to preprocess the tree data, I also encountered this problem sometimes. Maybe you can choose another server which has enough space to run this program? Or you can try to kill some proceeding program if necessary.
