### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by Sanathsharitsa** [WadeYin9712/SentiBERT#5]
Hi WadeYin, 

Can I run the existing codes on MacOS with Pycharm IDE with pytorch and python pre installed?

Sanath

**Comment by WadeYin9712** [comment]
Hi Sanath, thanks a lot for your interest! I'm not sure if it can be run on MacOS, since I never used Macbook laptops. It will be definitely better to find a Linux server by yourself. Though, it's still worth trying directly running it on your own laptop!

**Comment by Sanathsharitsa** [comment]
The only issue I'm afraid of is the GPU where in you have given in the
requirements as NVIDIA GTX 1080ti. The other stuff is manageable since I
code on pytorch, NLP and sentiment analysis very frequently on Mac OS.

My experiment would be to try to build a new algorithm like senti - Albert
and check it's performance. Do you have any suggestions for this?

Regards,
Sanath

**Comment by WadeYin9712** [comment]
Just wonder. Can you run originial BERT on Mac OS too?

For Albert, I may plan to revise and open source a code which could generally fit some of the transformer-based structures, including RoBERTa, Alberta, if I'm available in the future. One of the suggestions is that you can try to build your model on the current HuggingFace Transformer code. Thanks!

**Comment by Sanathsharitsa** [comment]
I'm planning to run it on a cloud based server rather than a new linux machine. 

So you mean to say that HuggingFace Transformer Code is dynamic and can be optimised to a transformer like or better than SentiBert? There is a lot of time that I would have to invest here to see different transformers on the internet and compare and try to build my own optimised model though. Thanks a lot for your input and time Wade :)!!

**Comment by WadeYin9712** [comment]
I mean Huggingface Transformer provides most of the existing popular Transformer structure like Albert and Roberta. You can try to  implement our work on other different Transformer models like Albert based on Huggingface Transformer, or you can also develop your own model on their code as well. Thanks, Sanath!

**Comment by Sanathsharitsa** [comment]
Thank you Wade. It was helpful :)
